name: CI/CD for RAG App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: thierrosyrius
          password: ${{ secrets.Github_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/thierrosyrius/oblicode_ai:latest .

      - name: Push Docker image
        run: docker push ghcr.io/thierrosyrius/oblicode_ai:latest

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/thierrosyrius/oblicode_ai:latest
            docker stop rag_app || true
            docker rm rag_app || true
            docker run -d -p 80:5001 --name rag_app ghcr.io/thierrosyrius/oblicode_ai:latest
